services:
  # === Xtion 側 ===
  ros2-xtion:
    image: sensor:latest
    container_name: ros2-xtion
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - AMENT_TRACE_SETUP_FILES=0
    volumes:
      - ${X11_DIR:-/tmp/.X11-unix}:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
      # - ./ros2_ws:/ros2_ws
    devices:
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 189:* rmw'
    ipc: "host"
    init: true
    restart: unless-stopped
    stdin_open: true
    tty: true
    # entrypoint: ["/bin/bash","-lc","set +u; . /opt/ros/humble/setup.bash; echo OK; sleep infinity"]
    entrypoint: ["/bin/bash","-lc",
      "set +u; \
       source /opt/ros/humble/setup.bash; \
       source /ros2_ws/install/setup.bash || true; \
       exec ros2 launch openni2_camera camera_only.launch.py"
    ]
    # 正常稼働の簡易ヘルスチェック：RGBトピックが出ているか
    healthcheck:
      test: ["CMD-SHELL",
            "source /opt/ros/humble/setup.bash && ros2 topic list | grep -q '^/camera/rgb/image_raw$'"]
      interval: 15s
      timeout: 5s
      retries: 5


  # === 推論側 ===
  perception:
    image: perception:latest
    container_name: perception
    network_mode: "host"
    privileged: true
    shm_size: "2g"
    runtime: "nvidia"
    gpus: "all"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - QT_X11_NO_MITSHM=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:128
    volumes:
      - ${X11_DIR:-/tmp/.X11-unix}:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/root/.Xauthority:rw
      - /dev/bus/usb:/dev/bus/usb
      - ${PWD}:/workspace
      - ./ros2_ws:/ros2_ws
    devices:
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 189:* rmw'
    ipc: "host"
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
